interface MTAComplex {
  stop_name: string;
  borough: string;
}

export const MTA_COMPLEX_ID_MAP: Record<string, MTAComplex> = {
  "17": { stop_name: "Prince St", borough: "Manhattan" },
  "68": { stop_name: "Bay Pkwy", borough: "Brooklyn" },
  "405": { stop_name: "23 St", borough: "Manhattan" },
  "152": { stop_name: "135 St", borough: "Manhattan" },
  "448": { stop_name: "Mets-Willets Point", borough: "Queens" },
  "254": { stop_name: "Jamaica-179 St", borough: "Queens" },
  "407": { stop_name: "Astor Pl", borough: "Manhattan" },
  "62": { stop_name: "55 St", borough: "Brooklyn" },
  "624": { stop_name: "Chambers St", borough: "Manhattan" },
  "455": { stop_name: "69 St", borough: "Queens" },
  "319": { stop_name: "28 St", borough: "Manhattan" },
  "371": { stop_name: "Hunts Point Av", borough: "The Bronx" },
  "425": { stop_name: "Bronx Park East", borough: "The Bronx" },
  "619": { stop_name: "Bleecker St", borough: "Manhattan" },
  "214": { stop_name: "182-183 Sts", borough: "The Bronx" },
  "340": { stop_name: "Grand Army Plaza", borough: "Brooklyn" },
  "217": { stop_name: "170 St", borough: "The Bronx" },
  "613": { stop_name: "Lexington Av/59 St", borough: "Manhattan" },
  "324": { stop_name: "Houston St", borough: "Manhattan" },
  "199": { stop_name: "Broad Channel", borough: "Queens" },
  "58": { stop_name: "Coney Island-Stillwell Av", borough: "Brooklyn" },
  "429": { stop_name: "Freeman St", borough: "The Bronx" },
  "601": { stop_name: "14 St", borough: "Manhattan" },
  "439": { stop_name: "125 St", borough: "Manhattan" },
  "42": { stop_name: "Prospect Park", borough: "Brooklyn" },
  "422": { stop_name: "Burke Av", borough: "The Bronx" },
  "100": { stop_name: "Hewes St", borough: "Brooklyn" },
  "278": { stop_name: "Jamaica Center-Parsons/Archer", borough: "Queens" },
  "339": { stop_name: "Bergen St", borough: "Brooklyn" },
  "245": { stop_name: "18 Av", borough: "Brooklyn" },
  "103": { stop_name: "Bowery", borough: "Manhattan" },
  "231": { stop_name: "Grand St", borough: "Manhattan" },
  "447": { stop_name: "Flushing-Main St", borough: "Queens" },
  "603": { stop_name: "149 St-Grand Concourse", borough: "The Bronx" },
  "93": { stop_name: "Chauncey St", borough: "Brooklyn" },
  "309": { stop_name: "103 St", borough: "Manhattan" },
  "385": { stop_name: "176 St", borough: "The Bronx" },
  "175": { stop_name: "Hoyt-Schermerhorn Sts", borough: "Brooklyn" },
  "33": { stop_name: "45 St", borough: "Brooklyn" },
  "289": { stop_name: "Bedford-Nostrand Avs", borough: "Brooklyn" },
  "10": { stop_name: "49 St", borough: "Manhattan" },
  "162": { stop_name: "50 St", borough: "Manhattan" },
  "477": { stop_name: "72 St", borough: "Manhattan" },
  "138": { stop_name: "Canarsie-Rockaway Pkwy", borough: "Brooklyn" },
  "518": { stop_name: "Pleasant Plains", borough: "Staten Island" },
  "67": { stop_name: "20 Av", borough: "Brooklyn" },
  "414": { stop_name: "Bowling Green", borough: "Manhattan" },
  "221": { stop_name: "21 St-Queensbridge", borough: "Queens" },
  "457": { stop_name: "52 St", borough: "Queens" },
  "451": { stop_name: "Junction Blvd", borough: "Queens" },
  "144": { stop_name: "Dyckman St", borough: "Manhattan" },
  "108": { stop_name: "Middle Village-Metropolitan Av", borough: "Queens" },
  "47": { stop_name: "Newkirk Plaza", borough: "Brooklyn" },
  "52": { stop_name: "Avenue U", borough: "Brooklyn" },
  "610": { stop_name: "Grand Central-42 St", borough: "Manhattan" },
  "337": { stop_name: "Nevins St", borough: "Brooklyn" },
  "8": { stop_name: "5 Av/59 St", borough: "Manhattan" },
  "417": { stop_name: "Nereid Av", borough: "The Bronx" },
  "519": { stop_name: "Richmond Valley", borough: "Staten Island" },
  "89": { stop_name: "Cleveland St", borough: "Brooklyn" },
  "95": { stop_name: "Gates Av", borough: "Brooklyn" },
  "192": { stop_name: "Rockaway Blvd", borough: "Queens" },
  "296": { stop_name: "Marble Hill-225 St", borough: "Manhattan" },
  "54": { stop_name: "Sheepshead Bay", borough: "Brooklyn" },
  "445": { stop_name: "Pelham Pkwy", borough: "The Bronx" },
  "194": { stop_name: "111 St", borough: "Queens" },
  "51": { stop_name: "Kings Hwy", borough: "Brooklyn" },
  "167": { stop_name: "W 4 St-Wash Sq", borough: "Manhattan" },
  "320": { stop_name: "23 St", borough: "Manhattan" },
  "438": { stop_name: "135 St", borough: "Manhattan" },
  "440": { stop_name: "116 St", borough: "Manhattan" },
  "80": { stop_name: "121 St", borough: "Queens" },
  "314": { stop_name: "66 St-Lincoln Center", borough: "Manhattan" },
  "409": { stop_name: "Spring St", borough: "Manhattan" },
  "461": { stop_name: "Queensboro Plaza", borough: "Queens" },
  "386": { stop_name: "Mt Eden Av", borough: "The Bronx" },
  "374": { stop_name: "E 143 St-St Mary's St", borough: "The Bronx" },
  "297": { stop_name: "215 St", borough: "Manhattan" },
  "450": { stop_name: "103 St-Corona Plaza", borough: "Queens" },
  "615": { stop_name: "62 St", borough: "Brooklyn" },
  "396": { stop_name: "96 St", borough: "Manhattan" },
  "503": { stop_name: "Stapleton", borough: "Staten Island" },
  "261": { stop_name: "Forest Hills-71 Av", borough: "Queens" },
  "397": { stop_name: "86 St", borough: "Manhattan" },
  "101": { stop_name: "Marcy Av", borough: "Brooklyn" },
  "312": { stop_name: "79 St", borough: "Manhattan" },
  "205": { stop_name: "Beach 60 St", borough: "Queens" },
  "350": { stop_name: "Pennsylvania Av", borough: "Brooklyn" },
  "45": { stop_name: "Beverley Rd", borough: "Brooklyn" },
  "313": { stop_name: "72 St", borough: "Manhattan" },
  "428": { stop_name: "174 St", borough: "The Bronx" },
  "249": { stop_name: "Avenue P", borough: "Brooklyn" },
  "398": { stop_name: "77 St", borough: "Manhattan" },
  "126": { stop_name: "Jefferson St", borough: "Brooklyn" },
  "459": { stop_name: "40 St-Lowery St", borough: "Queens" },
  "352": { stop_name: "New Lots Av", borough: "Brooklyn" },
  "50": { stop_name: "Avenue M", borough: "Brooklyn" },
  "268": { stop_name: "65 St", borough: "Queens" },
  "185": { stop_name: "Liberty Av", borough: "Brooklyn" },
  "86": { stop_name: "Cypress Hills", borough: "Brooklyn" },
  "506": { stop_name: "Old Town", borough: "Staten Island" },
  "240": { stop_name: "7 Av", borough: "Brooklyn" },
  "294": { stop_name: "238 St", borough: "The Bronx" },
  "343": { stop_name: "Nostrand Av", borough: "Brooklyn" },
  "382": { stop_name: "Fordham Rd", borough: "The Bronx" },
  "260": { stop_name: "75 Av", borough: "Queens" },
  "202": { stop_name: "Beach 105 St", borough: "Queens" },
  "79": { stop_name: "86 St", borough: "Brooklyn" },
  "220": { stop_name: "155 St", borough: "Manhattan" },
  "41": { stop_name: "7 Av", borough: "Brooklyn" },
  "453": { stop_name: "82 St-Jackson Hts", borough: "Queens" },
  "61": { stop_name: "50 St", borough: "Brooklyn" },
  "186": { stop_name: "Van Siclen Av", borough: "Brooklyn" },
  "90": { stop_name: "Van Siclen Av", borough: "Brooklyn" },
  "98": { stop_name: "Flushing Av", borough: "Brooklyn" },
  "257": { stop_name: "Sutphin Blvd", borough: "Queens" },
  "629": { stop_name: "Lorimer St", borough: "Brooklyn" },
  "387": { stop_name: "170 St", borough: "The Bronx" },
  "131": { stop_name: "Bushwick Av-Aberdeen St", borough: "Brooklyn" },
  "291": { stop_name: "Clinton-Washington Avs", borough: "Brooklyn" },
  "323": { stop_name: "Christopher St-Stonewall", borough: "Manhattan" },
  "449": { stop_name: "111 St", borough: "Queens" },
  "392": { stop_name: "125 St", borough: "Manhattan" },
  "5": { stop_name: "36 Av", borough: "Queens" },
  "306": { stop_name: "125 St", borough: "Manhattan" },
  "293": { stop_name: "Van Cortlandt Park-242 St", borough: "The Bronx" },
  "141": { stop_name: "Park Pl", borough: "Brooklyn" },
  "347": { stop_name: "Saratoga Av", borough: "Brooklyn" },
  "476": { stop_name: "86 St", borough: "Manhattan" },
  "189": { stop_name: "Grant Av", borough: "Brooklyn" },
  "617": { stop_name: "Atlantic Av-Barclays Ctr", borough: "Brooklyn" },
  "43": { stop_name: "Parkside Av", borough: "Brooklyn" },
  "508": { stop_name: "Jefferson Av", borough: "Staten Island" },
  "430": { stop_name: "Simpson St", borough: "The Bronx" },
  "635": { stop_name: "Whitehall St-South Ferry", borough: "Manhattan" },
  "235": { stop_name: "York St", borough: "Brooklyn" },
  "201": { stop_name: "Beach 98 St", borough: "Queens" },
  "463": { stop_name: "Hunters Point Av", borough: "Queens" },
  "622": { stop_name: "Brooklyn Bridge-City Hall", borough: "Manhattan" },
  "328": { stop_name: "WTC Cortlandt", borough: "Manhattan" },
  "361": { stop_name: "Buhre Av", borough: "The Bronx" },
  "4": { stop_name: "Broadway", borough: "Queens" },
  "434": { stop_name: "3 Av-149 St", borough: "The Bronx" },
  "130": { stop_name: "Wilson Av", borough: "Brooklyn" },
  "360": { stop_name: "Pelham Bay Park", borough: "The Bronx" },
  "282": { stop_name: "21 St", borough: "Queens" },
  "223": { stop_name: "Lexington Av/63 St", borough: "Manhattan" },
  "210": { stop_name: "Norwood-205 St", borough: "The Bronx" },
  "626": {
    stop_name: "Franklin Av-Medgar Evers College",
    borough: "Brooklyn",
  },
  "48": { stop_name: "Avenue H", borough: "Brooklyn" },
  "357": { stop_name: "Beverly Rd", borough: "Brooklyn" },
  "37": { stop_name: "77 St", borough: "Brooklyn" },
  "446": { stop_name: "Morris Park", borough: "The Bronx" },
  "87": { stop_name: "Crescent St", borough: "Brooklyn" },
  "153": { stop_name: "125 St", borough: "Manhattan" },
  "176": { stop_name: "Lafayette Av", borough: "Brooklyn" },
  "512": { stop_name: "Bay Terrace", borough: "Staten Island" },
  "232": { stop_name: "2 Av", borough: "Manhattan" },
  "424": { stop_name: "Pelham Pkwy", borough: "The Bronx" },
  "388": { stop_name: "167 St", borough: "The Bronx" },
  "123": { stop_name: "Grand St", borough: "Brooklyn" },
  "509": { stop_name: "Grant City", borough: "Staten Island" },
  "628": { stop_name: "Fulton St", borough: "Manhattan" },
  "609": { stop_name: "42 St-Bryant Pk", borough: "Manhattan" },
  "299": { stop_name: "Dyckman St", borough: "Manhattan" },
  "193": { stop_name: "104 St", borough: "Queens" },
  "372": { stop_name: "Longwood Av", borough: "The Bronx" },
  "334": { stop_name: "Clark St", borough: "Brooklyn" },
  "611": { stop_name: "Times Sq-42 St", borough: "Manhattan" },
  "608": { stop_name: "4 Av-9 St", borough: "Brooklyn" },
  "271": { stop_name: "Steinway St", borough: "Queens" },
  "316": { stop_name: "50 St", borough: "Manhattan" },
  "510": { stop_name: "New Dorp", borough: "Staten Island" },
  "228": { stop_name: "23 St", borough: "Manhattan" },
  "206": { stop_name: "Beach 44 St", borough: "Queens" },
  "505": { stop_name: "Grasmere", borough: "Staten Island" },
  "149": { stop_name: "163 St-Amsterdam Av", borough: "Manhattan" },
  "147": { stop_name: "175 St", borough: "Manhattan" },
  "66": { stop_name: "18 Av", borough: "Brooklyn" },
  "612": { stop_name: "Lexington Av/53 St", borough: "Manhattan" },
  "211": { stop_name: "Bedford Park Blvd", borough: "The Bronx" },
  "605": { stop_name: "168 St-Washington Hts", borough: "Manhattan" },
  "269": { stop_name: "Northern Blvd", borough: "Queens" },
  "287": { stop_name: "Flushing Av", borough: "Brooklyn" },
  "203": { stop_name: "Rockaway Park-Beach 116 St", borough: "Queens" },
  "74": { stop_name: "18 Av", borough: "Brooklyn" },
  "76": { stop_name: "Bay Pkwy", borough: "Brooklyn" },
  "137": { stop_name: "East 105 St", borough: "Brooklyn" },
  "129": { stop_name: "Halsey St", borough: "Queens" },
  "65": { stop_name: "79 St", borough: "Brooklyn" },
  "413": { stop_name: "Wall St", borough: "Manhattan" },
  "292": { stop_name: "Fulton St", borough: "Brooklyn" },
  "243": { stop_name: "Church Av", borough: "Brooklyn" },
  "241": { stop_name: "15 St-Prospect Park", borough: "Brooklyn" },
  "127": { stop_name: "DeKalb Av", borough: "Brooklyn" },
  "136": { stop_name: "New Lots Av", borough: "Brooklyn" },
  "179": { stop_name: "Nostrand Av", borough: "Brooklyn" },
  "242": { stop_name: "Fort Hamilton Pkwy", borough: "Brooklyn" },
  "146": { stop_name: "181 St", borough: "Manhattan" },
  "107": { stop_name: "Broad St", borough: "Manhattan" },
  "28": { stop_name: "Union St", borough: "Brooklyn" },
  "255": { stop_name: "169 St", borough: "Queens" },
  "22": { stop_name: "Rector St", borough: "Manhattan" },
  "91": { stop_name: "Alabama Av", borough: "Brooklyn" },
  "248": { stop_name: "Avenue N", borough: "Brooklyn" },
  "111": { stop_name: "Seneca Av", borough: "Queens" },
  "348": { stop_name: "Rockaway Av", borough: "Brooklyn" },
  "53": { stop_name: "Neck Rd", borough: "Brooklyn" },
  "286": { stop_name: "Broadway", borough: "Brooklyn" },
  "97": { stop_name: "Myrtle Av", borough: "Brooklyn" },
  "120": { stop_name: "Bedford Av", borough: "Brooklyn" },
  "290": { stop_name: "Classon Av", borough: "Brooklyn" },
  "20": { stop_name: "City Hall", borough: "Manhattan" },
  "416": { stop_name: "Wakefield-241 St", borough: "The Bronx" },
  "616": { stop_name: "Jackson Hts-Roosevelt Av", borough: "Queens" },
  "32": { stop_name: "36 St", borough: "Brooklyn" },
  "85": { stop_name: "75 St-Elderts Ln", borough: "Queens" },
  "49": { stop_name: "Avenue J", borough: "Brooklyn" },
  "35": { stop_name: "59 St", borough: "Brooklyn" },
  "367": { stop_name: "St Lawrence Av", borough: "The Bronx" },
  "618": { stop_name: "14 St", borough: "Manhattan" },
  "344": { stop_name: "Kingston Av", borough: "Brooklyn" },
  "264": { stop_name: "Woodhaven Blvd", borough: "Queens" },
  "283": { stop_name: "Greenpoint Av", borough: "Brooklyn" },
  "31": { stop_name: "25 St", borough: "Brooklyn" },
  "456": { stop_name: "61 St-Woodside", borough: "Queens" },
  "157": { stop_name: "96 St", borough: "Manhattan" },
  "514": { stop_name: "Eltingville", borough: "Staten Island" },
  "517": { stop_name: "Prince's Bay", borough: "Staten Island" },
  "75": { stop_name: "20 Av", borough: "Brooklyn" },
  "94": { stop_name: "Halsey St", borough: "Brooklyn" },
  "625": { stop_name: "Delancey St-Essex St", borough: "Manhattan" },
  "133": { stop_name: "Atlantic Av", borough: "Brooklyn" },
  "218": { stop_name: "167 St", borough: "The Bronx" },
  "276": { stop_name: "5 Av/53 St", borough: "Manhattan" },
  "394": { stop_name: "110 St", borough: "Manhattan" },
  "404": { stop_name: "28 St", borough: "Manhattan" },
  "78": { stop_name: "Avenue U", borough: "Brooklyn" },
  "441": { stop_name: "Central Park North (110 St)", borough: "Manhattan" },
  "349": { stop_name: "Junius St", borough: "Brooklyn" },
  "191": { stop_name: "88 St", borough: "Queens" },
  "620": { stop_name: "Borough Hall", borough: "Brooklyn" },
  "96": { stop_name: "Kosciuszko St", borough: "Brooklyn" },
  "378": { stop_name: "Woodlawn", borough: "The Bronx" },
  "507": { stop_name: "Dongan Hills", borough: "Staten Island" },
  "234": { stop_name: "East Broadway", borough: "Manhattan" },
  "630": { stop_name: "Myrtle-Wyckoff Avs", borough: "Brooklyn" },
  "164": { stop_name: "34 St-Penn Station", borough: "Manhattan" },
  "173": { stop_name: "High St", borough: "Brooklyn" },
  "636": { stop_name: "Jay St-MetroTech", borough: "Brooklyn" },
  "30": { stop_name: "Prospect Av", borough: "Brooklyn" },
  "303": { stop_name: "157 St", borough: "Manhattan" },
  "353": {
    stop_name: "President St-Medgar Evers College",
    borough: "Brooklyn",
  },
  "253": { stop_name: "Neptune Av", borough: "Brooklyn" },
  "114": { stop_name: "Central Av", borough: "Brooklyn" },
  "627": { stop_name: "Franklin Av", borough: "Brooklyn" },
  "311": { stop_name: "86 St", borough: "Manhattan" },
  "213": { stop_name: "Fordham Rd", borough: "The Bronx" },
  "256": { stop_name: "Parsons Blvd", borough: "Queens" },
  "391": { stop_name: "138 St-Grand Concourse", borough: "The Bronx" },
  "381": { stop_name: "Kingsbridge Rd", borough: "The Bronx" },
  "273": { stop_name: "Queens Plaza", borough: "Queens" },
  "122": { stop_name: "Graham Av", borough: "Brooklyn" },
  "57": { stop_name: "W 8 St-NY Aquarium", borough: "Brooklyn" },
  "351": { stop_name: "Van Siclen Av", borough: "Brooklyn" },
  "46": { stop_name: "Cortelyou Rd", borough: "Brooklyn" },
  "1": { stop_name: "Astoria-Ditmars Blvd", borough: "Queens" },
  "270": { stop_name: "46 St", borough: "Queens" },
  "247": { stop_name: "Bay Pkwy", borough: "Brooklyn" },
  "187": { stop_name: "Shepherd Av", borough: "Brooklyn" },
  "379": { stop_name: "Mosholu Pkwy", borough: "The Bronx" },
  "266": { stop_name: "Elmhurst Av", borough: "Queens" },
  "190": { stop_name: "80 St", borough: "Queens" },
  "155": { stop_name: "Cathedral Pkwy (110 St)", borough: "Manhattan" },
  "307": { stop_name: "116 St-Columbia University", borough: "Manhattan" },
  "326": { stop_name: "Franklin St", borough: "Manhattan" },
  "288": { stop_name: "Myrtle-Willoughby Avs", borough: "Brooklyn" },
  "426": { stop_name: "E 180 St", borough: "The Bronx" },
  "83": { stop_name: "Woodhaven Blvd", borough: "Queens" },
  "81": { stop_name: "111 St", borough: "Queens" },
  "99": { stop_name: "Lorimer St", borough: "Brooklyn" },
  "310": { stop_name: "96 St", borough: "Manhattan" },
  "215": { stop_name: "Tremont Av", borough: "The Bronx" },
  "180": { stop_name: "Kingston-Throop Avs", borough: "Brooklyn" },
  "376": { stop_name: "Brook Av", borough: "The Bronx" },
  "64": { stop_name: "71 St", borough: "Brooklyn" },
  "370": { stop_name: "Whitlock Av", borough: "The Bronx" },
  "363": { stop_name: "Westchester Sq-E Tremont Av", borough: "The Bronx" },
  "308": { stop_name: "Cathedral Pkwy (110 St)", borough: "Manhattan" },
  "222": { stop_name: "Roosevelt Island", borough: "Manhattan" },
  "356": { stop_name: "Church Av", borough: "Brooklyn" },
  "458": { stop_name: "46 St-Bliss St", borough: "Queens" },
  "346": { stop_name: "Sutter Av-Rutland Rd", borough: "Brooklyn" },
  "354": { stop_name: "Sterling St", borough: "Brooklyn" },
  "158": { stop_name: "86 St", borough: "Manhattan" },
  "154": { stop_name: "116 St", borough: "Manhattan" },
  "511": { stop_name: "Oakwood Heights", borough: "Staten Island" },
  "250": { stop_name: "Kings Hwy", borough: "Brooklyn" },
  "375": { stop_name: "Cypress Av", borough: "The Bronx" },
  "365": { stop_name: "Castle Hill Av", borough: "The Bronx" },
  "216": { stop_name: "174-175 Sts", borough: "The Bronx" },
  "295": { stop_name: "231 St", borough: "The Bronx" },
  "181": { stop_name: "Utica Av", borough: "Brooklyn" },
  "84": { stop_name: "85 St-Forest Pkwy", borough: "Queens" },
  "444": { stop_name: "Gun Hill Rd", borough: "The Bronx" },
  "325": { stop_name: "Canal St", borough: "Manhattan" },
  "333": { stop_name: "Wall St", borough: "Manhattan" },
  "70": { stop_name: "Bay 50 St", borough: "Brooklyn" },
  "427": { stop_name: "West Farms Sq-E Tremont Av", borough: "The Bronx" },
  "423": { stop_name: "Allerton Av", borough: "The Bronx" },
  "145": { stop_name: "190 St", borough: "Manhattan" },
  "60": { stop_name: "Fort Hamilton Pkwy", borough: "Brooklyn" },
  "272": { stop_name: "36 St", borough: "Queens" },
  "623": { stop_name: "Canal St", borough: "Manhattan" },
  "59": { stop_name: "9 Av", borough: "Brooklyn" },
  "621": { stop_name: "Broadway Junction", borough: "Brooklyn" },
  "200": { stop_name: "Beach 90 St", borough: "Queens" },
  "452": { stop_name: "90 St-Elmhurst Av", borough: "Queens" },
  "607": { stop_name: "34 St-Herald Sq", borough: "Manhattan" },
  "279": {
    stop_name: "Sutphin Blvd-Archer Av-JFK Airport",
    borough: "Queens",
  },
  "368": { stop_name: "Morrison Av-Soundview", borough: "The Bronx" },
  "207": { stop_name: "Beach 36 St", borough: "Queens" },
  "464": { stop_name: "Vernon Blvd-Jackson Av", borough: "Queens" },
  "44": { stop_name: "Church Av", borough: "Brooklyn" },
  "69": { stop_name: "25 Av", borough: "Brooklyn" },
  "265": { stop_name: "Grand Av-Newtown", borough: "Queens" },
  "39": { stop_name: "Bay Ridge-95 St", borough: "Brooklyn" },
  "399": { stop_name: "68 St-Hunter College", borough: "Manhattan" },
  "165": { stop_name: "23 St", borough: "Manhattan" },
  "420": { stop_name: "219 St", borough: "The Bronx" },
  "513": { stop_name: "Great Kills", borough: "Staten Island" },
  "204": { stop_name: "Beach 67 St", borough: "Queens" },
  "72": { stop_name: "Fort Hamilton Pkwy", borough: "Brooklyn" },
  "212": { stop_name: "Kingsbridge Rd", borough: "The Bronx" },
  "252": { stop_name: "Avenue X", borough: "Brooklyn" },
  "251": { stop_name: "Avenue U", borough: "Brooklyn" },
  "604": { stop_name: "161 St-Yankee Stadium", borough: "The Bronx" },
  "373": { stop_name: "E 149 St", borough: "The Bronx" },
  "151": { stop_name: "145 St", borough: "Manhattan" },
  "182": { stop_name: "Ralph Av", borough: "Brooklyn" },
  "143": { stop_name: "Inwood-207 St", borough: "Manhattan" },
  "336": { stop_name: "Hoyt St", borough: "Brooklyn" },
  "159": {
    stop_name: "81 St-Museum of Natural History",
    borough: "Manhattan",
  },
  "355": { stop_name: "Winthrop St", borough: "Brooklyn" },
  "134": { stop_name: "Sutter Av", borough: "Brooklyn" },
  "305": { stop_name: "137 St-City College", borough: "Manhattan" },
  "55": { stop_name: "Brighton Beach", borough: "Brooklyn" },
  "377": { stop_name: "3 Av-138 St", borough: "The Bronx" },
  "258": { stop_name: "Briarwood", borough: "Queens" },
  "168": { stop_name: "Spring St", borough: "Manhattan" },
  "246": { stop_name: "Avenue I", borough: "Brooklyn" },
  "160": { stop_name: "72 St", borough: "Manhattan" },
  "304": { stop_name: "145 St", borough: "Manhattan" },
  "118": { stop_name: "3 Av", borough: "Manhattan" },
  "522": { stop_name: "Tottenville", borough: "Staten Island" },
  "13": { stop_name: "28 St", borough: "Manhattan" },
  "177": { stop_name: "Clinton-Washington Avs", borough: "Brooklyn" },
  "432": { stop_name: "Prospect Av", borough: "The Bronx" },
  "504": { stop_name: "Clifton", borough: "Staten Island" },
  "421": { stop_name: "Gun Hill Rd", borough: "The Bronx" },
  "442": { stop_name: "Eastchester-Dyre Av", borough: "The Bronx" },
  "395": { stop_name: "103 St", borough: "Manhattan" },
  "77": { stop_name: "Kings Hwy", borough: "Brooklyn" },
  "359": { stop_name: "Flatbush Av-Brooklyn College", borough: "Brooklyn" },
  "263": { stop_name: "63 Dr-Rego Park", borough: "Queens" },
  "71": { stop_name: "8 Av", borough: "Brooklyn" },
  "614": { stop_name: "59 St-Columbus Circle", borough: "Manhattan" },
  "38": { stop_name: "86 St", borough: "Brooklyn" },
  "188": { stop_name: "Euclid Av", borough: "Brooklyn" },
  "56": { stop_name: "Ocean Pkwy", borough: "Brooklyn" },
  "380": {
    stop_name: "Bedford Park Blvd-Lehman College",
    borough: "The Bronx",
  },
  "418": { stop_name: "233 St", borough: "The Bronx" },
  "209": { stop_name: "Far Rockaway-Mott Av", borough: "Queens" },
  "516": { stop_name: "Huguenot", borough: "Staten Island" },
  "244": { stop_name: "Ditmas Av", borough: "Brooklyn" },
  "403": { stop_name: "33 St", borough: "Manhattan" },
  "431": { stop_name: "Intervale Av", borough: "The Bronx" },
  "36": { stop_name: "Bay Ridge Av", borough: "Brooklyn" },
  "364": { stop_name: "Zerega Av", borough: "The Bronx" },
  "515": { stop_name: "Annadale", borough: "Staten Island" },
  "113": { stop_name: "Knickerbocker Av", borough: "Brooklyn" },
  "135": { stop_name: "Livonia Av", borough: "Brooklyn" },
  "318": { stop_name: "34 St-Penn Station", borough: "Manhattan" },
  "109": { stop_name: "Fresh Pond Rd", borough: "Queens" },
  "125": { stop_name: "Morgan Av", borough: "Brooklyn" },
  "169": { stop_name: "Canal St", borough: "Manhattan" },
  "362": { stop_name: "Middletown Rd", borough: "The Bronx" },
  "198": { stop_name: "Howard Beach-JFK Airport", borough: "Queens" },
  "124": { stop_name: "Montrose Av", borough: "Brooklyn" },
  "208": { stop_name: "Beach 25 St", borough: "Queens" },
  "9": { stop_name: "57 St-7 Av", borough: "Manhattan" },
  "196": { stop_name: "Aqueduct Racetrack", borough: "Queens" },
  "327": { stop_name: "Chambers St", borough: "Manhattan" },
  "259": { stop_name: "Kew Gardens-Union Tpke", borough: "Queens" },
  "197": { stop_name: "Aqueduct-N Conduit Av", borough: "Queens" },
  "183": { stop_name: "Rockaway Av", borough: "Brooklyn" },
  "3": { stop_name: "30 Av", borough: "Queens" },
  "277": { stop_name: "7 Av", borough: "Manhattan" },
  "195": { stop_name: "Ozone Park-Lefferts Blvd", borough: "Queens" },
  "119": { stop_name: "1 Av", borough: "Manhattan" },
  "502": { stop_name: "Tompkinsville", borough: "Staten Island" },
  "471": { stop_name: "34 St-Hudson Yards", borough: "Manhattan" },
  "82": { stop_name: "104 St", borough: "Queens" },
  "156": { stop_name: "103 St", borough: "Manhattan" },
  "2": { stop_name: "Astoria Blvd", borough: "Queens" },
  "262": { stop_name: "67 Av", borough: "Queens" },
  "602": { stop_name: "14 St-Union Sq", borough: "Manhattan" },
  "150": { stop_name: "155 St", borough: "Manhattan" },
  "523": { stop_name: "Arthur Kill", borough: "Staten Island" },
  "238": { stop_name: "Smith-9 Sts", borough: "Brooklyn" },
  "345": { stop_name: "Crown Hts-Utica Av", borough: "Brooklyn" },
  "366": { stop_name: "Parkchester", borough: "The Bronx" },
  "237": { stop_name: "Carroll St", borough: "Brooklyn" },
  "321": { stop_name: "18 St", borough: "Manhattan" },
  "298": { stop_name: "207 St", borough: "Manhattan" },
  "384": { stop_name: "Burnside Av", borough: "The Bronx" },
  "436": { stop_name: "Harlem-148 St", borough: "Manhattan" },
  "110": { stop_name: "Forest Av", borough: "Queens" },
  "369": { stop_name: "Elder Av", borough: "The Bronx" },
  "437": { stop_name: "145 St", borough: "Manhattan" },
  "606": { stop_name: "Court Sq", borough: "Queens" },
  "16": { stop_name: "8 St-NYU", borough: "Manhattan" },
  "301": { stop_name: "181 St", borough: "Manhattan" },
  "34": { stop_name: "53 St", borough: "Brooklyn" },
  "393": { stop_name: "116 St", borough: "Manhattan" },
  "475": { stop_name: "96 St", borough: "Manhattan" },
  "383": { stop_name: "183 St", borough: "The Bronx" },
  "224": { stop_name: "57 St", borough: "Manhattan" },
  "501": { stop_name: "St George", borough: "Staten Island" },
  "443": { stop_name: "Baychester Av", borough: "The Bronx" },
  "358": { stop_name: "Newkirk Av-Little Haiti", borough: "Brooklyn" },
  "284": { stop_name: "Nassau Av", borough: "Brooklyn" },
  "6": { stop_name: "39 Av-Dutch Kills", borough: "Queens" },
  "300": { stop_name: "191 St", borough: "Manhattan" },
  "341": { stop_name: "Eastern Pkwy-Brooklyn Museum", borough: "Brooklyn" },
  "26": { stop_name: "DeKalb Av", borough: "Brooklyn" },
  "433": { stop_name: "Jackson Av", borough: "The Bronx" },
  "280": { stop_name: "Jamaica-Van Wyck", borough: "Queens" },
  "225": { stop_name: "47-50 Sts-Rockefeller Ctr", borough: "Manhattan" },
  "14": { stop_name: "23 St", borough: "Manhattan" },
  "236": { stop_name: "Bergen St", borough: "Brooklyn" },
  "88": { stop_name: "Norwood Av", borough: "Brooklyn" },
  "419": { stop_name: "225 St", borough: "The Bronx" },
  "460": { stop_name: "33 St-Rawson St", borough: "Queens" },
  "329": { stop_name: "Rector St", borough: "Manhattan" },
};
